name: prayer
version: 0.0.2

description: The prayer library is a framework for creating a prayer application.
homepage: https://github.com/fliturgy/prayer

environment:
  sdk: '^3.0.2'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  lints: ">=2.0.0 <4.0.0"
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  